### ISSUE TITLE
intersection modes "intersection" and "average" do not work for huge amounts of origins

### ISSUE THREAD

**Issue by 5chdn** [5chdn/webgl-accessibility-maps-poc5#31]
intersection modes "intersection" and "average" do not work for huge amounts of origins. huge => 5?

**Comment by gerbsen** [comment]
Es gibt gewisse Limits für jeden User die das regeln.. wieviele sources brauchst du denn?

**Comment by 5chdn** [comment]
32 wären super. würde gerne noch einen screenshot machen.

was sind denn die limits?

**Comment by gerbsen** [comment]
Welchen Key verwendest du? Unser Netzwerk ist gelayert, aktuell sind da 50 eingestellt. Wenn du jetzt mit 32 Sources kommst verbrauchst du 32 Layer.

**Comment by 5chdn** [comment]
ref. 7f58c1f029055991f04176eb456ce100f6aedf38
